Refactoring adding automapper to commands
PolishDevCom/SocialKnow pull request #29
Opened 2021-03-09 15:54 UTC by wystrzal

2021-03-19 12:01 UTC, matdon90 requested changes
Relatively good, two things I think need to change before merging. Have you checked if your enhancements break the integration tests?

2021-03-19 15:46 UTC, wystrzal commented on SK.Application/Discussions/Commands/CreateDiscussion/CreateDiscussionCommandHandler.cs
> -                IsClosed = false,
Automapper automatically sets the value to false if there is no specified value.

2021-03-20 17:52 UTC, UgzSourceCode approved these changes

2021-03-22 11:28 UTC, matdon90 approved these changes

2021-03-22 14:29 UTC, merged