Refactoring47 pagination service
PolishDevCom/SocialKnow pull request #50
Opened 2021-04-26 17:35 UTC by wystrzal

2021-04-27 10:57 UTC, matdon90 requested changes
Some minor changes and one related to code clarity.

2021-04-27 10:57 UTC, matdon90 commented on SK.Application/Articles/Queries/ListArticle/ListArticleQueryHandler.cs
> +        private readonly IPaginationService<Article, ArticleDto> paginationService;
Prefere to use underline before private field to avoid use "this." in constructor.

2021-04-27 10:57 UTC, matdon90 commented on SK.Application/Discussions/Queries/ListDiscussion/ListDiscussionQueryHandler.cs
> +        private readonly IPaginationService<Discussion, DiscussionDto> paginationService;
As above.

2021-04-27 10:57 UTC, matdon90 commented on SK.Application/Events/Queries/ListEvent/ListEventQueryHandler.cs
> +        private readonly IPaginationService<Event, EventDto> paginationService;
As above.

2021-04-27 10:57 UTC, matdon90 commented on SK.Application/Tags/Queries/ListTag/ListTagQueryHandler.cs
> +            this.paginationService = paginationService;
As above.

2021-04-27 10:57 UTC, matdon90 commented on SK.Infrastructure/Services/PaginationService.cs
> +            IOrderedQueryable<TEntity> orderedQueryable;
Imho, more clean would be with use of **?:** operator and the whole expression would be like **condition ? consequent : alternative** - in this case : **IOrderedQueryable<TEntity> orderedQueryable = descending ? _context.DbSet<TEntity>().OrderByDescending(additionalOrder) : _context.DbSet<TEntity>().OrderBy(additionalOrder)**

2021-05-09 17:41 UTC, UgzSourceCode approved these changes

2021-05-09 18:16 UTC, merged